### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by vaibhavsagar** [carlohamalainen/carlohamalainen.github.io#5]
Hi Carlo,

Can I trouble you to add an RSS feed for your blog?

Thanks,
Vaibhav

**Comment by carlohamalainen** [comment]
Does this work? https://carlo-hamalainen.net/feed.xml

The link is right at the bottom of the home page :-)

**Comment by vaibhavsagar** [comment]
Oh huh, I missed that link and didn't see an XML file in your project root so I thought you might not have one. Thank you and sorry for the hassle!
